[project]
name = "django-music-controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "django>=3.2.25",
    "djangorestframework>=3.15.1",
]
